name: cron-schedule-updater
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0,3'
 
jobs:
  empty_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - run: git config user.email "nepo@nies.futbol"
    - run: git config user.name "Nepo Rojas"

    - name: Create Empty Commit
      run: git commit --allow-empty -m "Empty commit"

    - name: Push Empty Commit
      run: git push origin master  # Change 'main' to your branch name
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
